/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;


import classes.Cartao;
import classes.Compra;
import classes.Constantes;
import conexao.FabricaDeConexao;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author danilo
 */
public class CadastroCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroConta
     */
    
    static ArrayList<Cartao> listaCartao = new ArrayList();
    static ArrayList<Cartao> adicionar = new ArrayList();
    
    public CadastroCompra(){ 
        initComponents();
        painel_Juros.setVisible(false);
        painel_entrada.setVisible(false);
        GregorianCalendar calendar = new GregorianCalendar();
        spn_dia.setValue(calendar.get(GregorianCalendar.DAY_OF_MONTH));
        spn_mes.setValue(calendar.get(GregorianCalendar.MONTH)+1);
        spn_ano.setValue(calendar.get(GregorianCalendar.YEAR));
        
        
        FabricaDeConexao conexao = new FabricaDeConexao();
        Cartao c = new Cartao();
        if(listaCartao.isEmpty()){
            c.setNome("empty");
            listaCartao.add(c);
        }
        if(adicionar.isEmpty()){
            adicionar.add(c);
        }
        ResultSet rs = conexao.obterResultSet("SELECT `nome` FROM `cartao` WHERE `id_usuario` = '"+Constantes.getID_USUARIO()+"';");
        boolean aceita=true;
        
        for(Cartao card : listaCartao){
            System.out.println(card.getNome());
        }
        
        try{
            
            while(rs.next()){
                
                for(Cartao card : listaCartao){
                    System.out.println("Nome Cartao: "+card.getNome());
                    System.out.println("Nome ResultSet: "+rs.getString("nome"));
                     if(card.getNome().equals(rs.getString("nome"))){
                        aceita = false;
                    }
                }
                if(aceita){
                    Cartao cartao = new Cartao();
                    cartao.setNome(rs.getString("nome"));
                    System.out.println("Nome adicionar: "+c.getNome());
                    adicionar.add(cartao);
                    combo_forma_pg.addItem(rs.getString("nome"), c);
                }
            }
            
            listaCartao.clear();
            
            for(Cartao card : adicionar){
                listaCartao.add(card);
                System.out.println(card.getNome());
            }
        }catch(SQLException e){
            
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spn_valor = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spn_vezes = new javax.swing.JSpinner();
        but_juros = new javax.swing.JRadioButton();
        painel_Juros = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spn_mesJuros = new javax.swing.JSpinner();
        spn_porc = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        btn_concluir = new javax.swing.JButton();
        but_entrada = new javax.swing.JRadioButton();
        painel_entrada = new javax.swing.JPanel();
        spn_entrada = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spn_dia = new javax.swing.JSpinner();
        spn_ano = new javax.swing.JSpinner();
        spn_mes = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        combo_forma_pg = new componentes.UJComboBox();

        setClosable(true);
        setTitle("Cadastro de Compra");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName(""); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Nome da Compra:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        txt_nome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 313, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Valor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        spn_valor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        spn_valor.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        jPanel1.add(spn_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 64, 95, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Forma de Pagamento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 62, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Vezes:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 187, -1, -1));

        spn_vezes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        spn_vezes.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(spn_vezes, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 189, 57, -1));

        but_juros.setText("JUROS");
        but_juros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_jurosActionPerformed(evt);
            }
        });
        jPanel1.add(but_juros, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 251, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Porcentagem:");

        jLabel6.setText("%");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("A partir do mês:");

        spn_mesJuros.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        spn_mesJuros.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        spn_porc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        spn_porc.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.0d));

        javax.swing.GroupLayout painel_JurosLayout = new javax.swing.GroupLayout(painel_Juros);
        painel_Juros.setLayout(painel_JurosLayout);
        painel_JurosLayout.setHorizontalGroup(
            painel_JurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_JurosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn_porc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn_mesJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        painel_JurosLayout.setVerticalGroup(
            painel_JurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_JurosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_JurosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(spn_mesJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spn_porc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel1.add(painel_Juros, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 242, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Data da Compra:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 189, -1, -1));

        btn_concluir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_concluir.setText("Concluir");
        btn_concluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_concluirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_concluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 285, -1));

        but_entrada.setText("ENTRADA");
        but_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_entradaActionPerformed(evt);
            }
        });
        jPanel1.add(but_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 130, -1, -1));

        spn_entrada.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        spn_entrada.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Valor de Entrada:");

        javax.swing.GroupLayout painel_entradaLayout = new javax.swing.GroupLayout(painel_entrada);
        painel_entrada.setLayout(painel_entradaLayout);
        painel_entradaLayout.setHorizontalGroup(
            painel_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_entradaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spn_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painel_entradaLayout.setVerticalGroup(
            painel_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_entradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spn_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.add(painel_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        spn_dia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        spn_dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        jPanel1.add(spn_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 50, -1));

        spn_ano.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        spn_ano.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(spn_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 80, -1));

        spn_mes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        spn_mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jPanel1.add(spn_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 50, -1));

        jLabel10.setText("dia");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel11.setText("mês");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel12.setText("ano");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        combo_forma_pg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dinheiro" }));
        combo_forma_pg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        combo_forma_pg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_forma_pgMouseClicked(evt);
            }
        });
        combo_forma_pg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_forma_pgActionPerformed(evt);
            }
        });
        combo_forma_pg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                combo_forma_pgPropertyChange(evt);
            }
        });
        jPanel1.add(combo_forma_pg, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_jurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_jurosActionPerformed
    
        if(painel_Juros.isVisible()){
            painel_Juros.setVisible(false);
        }else{
            painel_Juros.setVisible(true);
        }
    }//GEN-LAST:event_but_jurosActionPerformed

    private void but_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_entradaActionPerformed
        
        if(painel_entrada.isVisible()){
            painel_entrada.setVisible(false);
        }else{
            painel_entrada.setVisible(true);
        }
            
        
    }//GEN-LAST:event_but_entradaActionPerformed

    private void btn_concluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_concluirActionPerformed
        if(txt_nome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"O campo de nome não\npode estar vazio!","Aviso",2);
        }else{
            ArrayList<Compra> lista = new ArrayList();
            FabricaDeConexao con = new FabricaDeConexao();
            int i = combo_forma_pg.getSelectedIndex();
            System.out.println(i);
            //if(combo){
            //    ResultSet rs con.executeSQLQuery("SELECT ");
            //}
            
            //if(){

                int v=(int)spn_vezes.getValue();
                int mes = (int)spn_mes.getValue();
                int ano = (int)spn_ano.getValue();


                /*

                    !!!! Cadastro no Banco está funcionando !!!!

                    !!!! Lógica para Vezes de Pagamento !!!!

                    !!!! Pensar em uma chave identificadora para compra, independete das vezes !!!!

                    !!!! Implementar programação para calcular Juros !!!!

                    !!!! Programar as Validações necessárias para cadastro de compra !!!!

                    !!!! Criar a Interface para Cadastro de Formas de Pagamento !!!!

                    !!!! Programar a forma de Pagamento no Cadastro de Compra !!!!

                    !!!! Pesquisar Maneira de Colocar Objeto no JSpinner !!!!

                    > Validar Valor do Cartao com Compra

                    > Validar Criação de Cartão

                    > Mostrar Cartão criado sem ter que logar Novamente

                    > Criar Perfil de usuário

                    > Conferir Valores do INSERT de compras

                    > Mostrar compras

                */



                ResultSet rs;
                rs = con.obterResultSet("SELECT * FROM `compras` WHERE `codigo` = (SELECT MAX(`codigo`) FROM `compras`)");
                int codigo=0;
                try{
                    while(rs.next()){
                        codigo = rs.getInt("codigo")+1;
                    }
                }catch(SQLException e){
                }
                if(but_entrada.isSelected()){
                    Double valor = (double)spn_entrada.getValue();
                    con.executarQuery("INSERT INTO `compras` (`codigo`,`id_usuario`,`form_pagamento`,"
                        + "`nome`,`valor`,`vezes`,`parc_rest`,`data`) VALUES ('"+codigo+"','"+Constantes.getID_USUARIO()+
                        "','"+combo_forma_pg.getSelectedIndex()+"','"+txt_nome.getText()+"','"
                        +valor+"','"+spn_vezes.getValue()+"','"+v+"','"+
                        spn_ano.getValue()+"-"+spn_mes.getValue()+"-"+spn_dia.getValue()+"')");
                    spn_valor.setValue((double)spn_valor.getValue()-valor);
                }

                if(spn_vezes.getValue().equals(1)){
                    con.executarQuery("INSERT INTO `compras` (`codigo`,`id_usuario`,`form_pagamento`,"
                        + "`nome`,`valor`,`vezes`,`parc_rest`,`data`) VALUES ('"+codigo+"','"+Constantes.getID_USUARIO()+
                        "','"+combo_forma_pg.getSelectedIndex()+"','"+txt_nome.getText()+"','"
                        +spn_valor.getValue()+"','"+spn_vezes.getValue()+"','"+v+"','"+
                        spn_ano.getValue()+"-"+spn_mes.getValue()+"-"+spn_dia.getValue()+"')");
                }else{
                    double porc = 0;
                    if(but_juros.isSelected()){
                        porc = (double)spn_porc.getValue()/100;
                        int jMes;
                        porc = (double)spn_valor.getValue()*porc;
                    }
                    double valor = (double)spn_valor.getValue()/(int)spn_vezes.getValue();

                    for(int c=0;c<(int)spn_vezes.getValue();c++){
                        if((int)spn_mesJuros.getValue()==(c+1)){
                            valor += porc;
                        }
                        con.executarQuery("INSERT INTO `compras` (`codigo`,`id_usuario`,`form_pagamento`,"
                            + "`nome`,`valor`,`vezes`,`parc_rest`,`data`) VALUES ('"+codigo+"','"+Constantes.getID_USUARIO()+
                            "','"+combo_forma_pg.getSelectedIndex()+"','"+txt_nome.getText()+"','"
                            +(valor)+"','"+spn_vezes.getValue()+"','"+v+"','"+
                            ano+"-"+mes+"-"+spn_dia.getValue()+"')");
                        if(mes==12){
                            mes=0;
                            ano++;
                        }
                        v--;
                        mes++;
                    }

                }
                JOptionPane.showMessageDialog(null, "Compra cadastrada com\nsucesso!","Confirmação",1);
                txt_nome.setText(null);
                spn_valor.setValue(0);
                spn_entrada.setValue(0);
                if(but_entrada.isSelected()){
                    but_entrada.doClick();
                }
                spn_vezes.setValue(1);
                spn_porc.setValue(1);
                spn_mesJuros.setValue(1);
                if(but_juros.isSelected()){
                    but_juros.doClick();
                }
            //}
        }
        
    }//GEN-LAST:event_btn_concluirActionPerformed

    private void combo_forma_pgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_forma_pgActionPerformed
        
    }//GEN-LAST:event_combo_forma_pgActionPerformed

    private void combo_forma_pgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_forma_pgMouseClicked
        
    }//GEN-LAST:event_combo_forma_pgMouseClicked

    private void combo_forma_pgPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_combo_forma_pgPropertyChange
        
        
       
        
    }//GEN-LAST:event_combo_forma_pgPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_concluir;
    private javax.swing.JRadioButton but_entrada;
    private javax.swing.JRadioButton but_juros;
    private componentes.UJComboBox combo_forma_pg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painel_Juros;
    private javax.swing.JPanel painel_entrada;
    private javax.swing.JSpinner spn_ano;
    private javax.swing.JSpinner spn_dia;
    private javax.swing.JSpinner spn_entrada;
    private javax.swing.JSpinner spn_mes;
    private javax.swing.JSpinner spn_mesJuros;
    private javax.swing.JSpinner spn_porc;
    private javax.swing.JSpinner spn_valor;
    private javax.swing.JSpinner spn_vezes;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables
}
